name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all

  integration: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        base:
          - core
          - core18
          - core20
        arch:
          - ''
          - amd64
          - i386
          - armhf
          - arm64
          - ppc64el
        exclude:
          - base: core20
            arch: armhf
          - base: core20
            arch: i386
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt@sha256:df15403e06a03c2f461c1f7938b171fda34a5849eb63a70e2a2109ed5a778bde
    - uses: actions/checkout@v2
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.base }}'
        architecture: ${{ matrix.arch }}
